base_model: /Users/adeelarshad/Notebooks/models/TinyLlama-1.1B-Chat-v1.0
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer
datasets:
- path: /Users/adeelarshad/CorDA/ufone_synthetic_1000.jsonl
  type:
    system_prompt: You are a Network Support agent, answer the question based on the
      provided information. If you don't know the answer, say you don't know.
    field_system: system
    field_category: category
    field_instruction: question
    field_output: answer
    format: '<|system|>

      {system_prompt}</s>

      <|user|>

      {instruction}</s>


      <|assistant|>

      {answer}</s>

      '
    no_input_format: "<|system|>\n{system_prompt}</s>\n<|user|>\n{instruction}</s>\n\
      \n<|assistant|>\n{answer}</s>\n  \n"
output_dir: ./lat_corda_out
merged_dir: ./sft_merged_model
max_seq_length: 256
lora:
  r: 16
  alpha: 32
  dropout: 0.05
  target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj
training:
  batch_size: 1
  micro_batch_size: 2
  gradient_accumulation_steps: 2
  epochs: 2
  learning_rate: 0.0001
  gradient_checkpointing: true
optimizer: adamw_torch
lr_scheduler: cosine
train_on_inputs: false
group_by_length: true
gradient_checkpointing: true
logging_steps: 10
save_steps: 200
bf16: false
fp16: false
