base_model: /Users/adeelarshad/Notebooks/models/TinyLlama-1.1B-Chat-v1.0

model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer

datasets:
  - path: jaydenccc/AI_Storyteller_Dataset
    type: 
      system_prompt: ""
      field_system: system
      field_instruction: synopsis
      field_output: short_story
      format: "<|user|>\n {instruction} </s>\n<|assistant|>"
      no_input_format: "<|user|> {instruction} </s>\n<|assistant|>"
      
output_dir: ./corda_out
merged_dir: ./merged_model

max_seq_length: 512

# -------------------------
# LORA CONFIG (REQUIRED)
# -------------------------
lora:
  r: 8
  alpha: 16
  dropout: 0.05
  target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj

# -------------------------
# TRAINING CONFIG (REQUIRED)
# -------------------------
training:
  batch_size: 1
  micro_batch_size: 2
  gradient_accumulation_steps: 2
  epochs: 3
  learning_rate: 0.0002
  gradient_checkpointing: True

# -------------------------
# OPTIMIZATION
# -------------------------
optimizer: adamw_torch
lr_scheduler: cosine
train_on_inputs: false
group_by_length: true

gradient_checkpointing: true

# -------------------------
# LOGGING / SAVING
# -------------------------
logging_steps: 10
save_steps: 200

# -------------------------
# PRECISION (CPU SAFE)
# -------------------------
bf16: false
fp16: false

