#!/usr/bin/env python3
"""
TypeScript Contract Exporter
============================
Generates frontend/src/types/contracts.generated.ts from authoritative
Pydantic contracts in FikraCore (Tier 1) and Zaki (Tier 2).
"""

from pathlib import Path
import sys

# Add services/agents/src to path
repo_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(repo_root / "services" / "agents" / "src"))

output_file = repo_root / "frontend" / "src" / "types" / "contracts.generated.ts"
output_file.parent.mkdir(parents=True, exist_ok=True)

ts_content = """/**
 * Authoritative Telecommunications & Zaki NOC SME Contracts
 * Auto-generated by scripts/export_contract_types.py - DO NOT EDIT MANUALLY
 *
 * Grounded in:
 * - FikraCore Canonical 4-Plane Knowledge Graph (Tier 1)
 * - Zaki Operational Orchestration & Governance Engine (Tier 2)
 */

// ============================================================================
// 1. Core Primitives & Enums
// ============================================================================

export type DomainCode =
  | "RAN"
  | "IP_TRANSPORT"
  | "PS_CORE"
  | "CLOUD_INFRA"
  | "IMS_VOICE"
  | "SECURITY"
  | "OSS_MANAGEMENT"
  | "UNKNOWN";

export type AuthorityLevel =
  | "LEVEL_0_OBSERVE"
  | "LEVEL_1_ANALYZE"
  | "LEVEL_2_RECOMMEND"
  | "LEVEL_3_PLAN"
  | "LEVEL_4_HITL_EXECUTE"
  | "LEVEL_5_AUTO_EXECUTE";

export type ActionSafetyTier =
  | "READ_ONLY_DIAGNOSTIC"
  | "CONTROLLED_REVERSIBLE"
  | "DISRUPTIVE";

export type EvidenceTier =
  | "RAW"
  | "EMERGING"
  | "VALIDATED";

export type OperationalSignificance =
  | "WEAK_SIGNAL"
  | "ANOMALY_DETECTED"
  | "PRE_INCIDENT_CANDIDATE";

export type SeverityTrend =
  | "STABLE"
  | "ESCALATING"
  | "DE_ESCALATING";

export type HypothesisStatus =
  | "CANDIDATE"
  | "SUSPECTED"
  | "UNDER_VALIDATION"
  | "RULED_OUT"
  | "CONFIRMED"
  | "REJECTED";

export type EvidenceVerdict =
  | "SUPPORTS"
  | "CONTRADICTS"
  | "CONFIRMS"
  | "RULES_OUT";

export type BlastRadiusLevel =
  | "LOCAL"
  | "DOMAIN"
  | "MULTI_DOMAIN"
  | "REGIONAL"
  | "NETWORK_WIDE";

export type KnowledgePromotionState =
  | "CANDIDATE"
  | "UNDER_REVIEW"
  | "VALIDATED"
  | "PROMOTED"
  | "REJECTED"
  | "SUPERSEDED"
  | "STALE"
  | "CONTRADICTED"
  | "REVOKED";

export type ValidationDecisionType =
  | "ACCEPT"
  | "REJECT"
  | "MODIFY"
  | "NEED_MORE_EVIDENCE"
  | "CONFIRM"
  | "APPROVE_LEARNING";

// ============================================================================
// 2. Tier 1: Canonical System Contracts (FikraCore)
// ============================================================================

export interface RawEvidenceContract {
  telemetry_id: string;
  event_time: string;
  stream_source: string;
  raw_payload: Record<string, unknown>;
  ingestion_time?: string | null;
}

export interface EmergingEvidenceContract {
  emerging_id: string;
  signal_name: string;
  domain: string;
  target_entity: string;
  severity_trend: SeverityTrend;
  window_duration_seconds: number;
  aggregated_signal_count: number;
  observed_baseline_deviation: number;
  operational_significance: OperationalSignificance;
  first_seen: string;
  last_seen: string;
}

export interface Evidence {
  evidence_id: string;
  event_time: string;
  ingestion_time: string;
  domain: string;
  entity: string;
  canonical_entity: string;
  entity_type: string;
  service: string[];
  evidence_type: string;
  value?: unknown;
  signal: string;
  source: string;
  source_vendor: string;
  source_native_entity: string;
  source_reliability: number;
  freshness: number;
  observed_or_inferred: "OBSERVED" | "INFERRED" | "CONFIRMED" | "REJECTED";
  polarity: "abnormal" | "healthy" | "context" | "unknown";
  severity: string;
  observed_path: string[];
  duplicate_ids?: string[];
}

export interface ValidatedEvidenceContract {
  evidence_id: string;
  canonical_entity: string;
  domain: string;
  verdict: EvidenceVerdict;
  corroborating_hypotheses: string[];
  confidence: number;
  validated_by_agent: string;
  timestamp: string;
}

export interface BlastRadiusAssessment {
  directly_affected_entities: string[];
  indirectly_affected_entities: string[];
  affected_services: string[];
  affected_domains?: string[];
  affected_regions?: string[];
  blast_radius_level: BlastRadiusLevel;
  confidence?: number;
  customer_facing_impact?: string;
}

export interface InvestigationHypothesis {
  hypothesis_id: string;
  statement: string;
  candidate_root_domain: string;
  candidate_root_entity: string;
  canonical_root_entity: string;
  root_entities: string[];
  causal_role: string;
  assumptions: Array<{ statement: string; state: string; evidence_ids: string[] }>;
  expected_observations: string[];
  supporting_evidence: string[];
  contradicting_evidence: string[];
  missing_evidence: string[];
  knowledge_relationships_used: string[];
  status: HypothesisStatus;
  hypothesis_confidence: number;
  causal_confidence: number;
  explanation_coverage: number;
  score_dimensions: Record<string, number>;
  failed_assumptions?: string[];
}

export interface RemediationPlaybookContract {
  playbook_id: string;
  name: string;
  target_domains: string[];
  safety_tier: ActionSafetyTier;
  target_fault_modes: string[];
  estimated_execution_seconds: number;
  preconditions: Array<{
    precondition_id: string;
    description: string;
    required_state: string;
    target_entity: string;
    verified: boolean;
  }>;
  execution_steps: Array<{
    step_number: number;
    action_name: string;
    target_node: string;
    command_template: string;
    safety_tier: ActionSafetyTier;
  }>;
  rollback_steps: Array<{
    step_number: number;
    rollback_action: string;
    target_node: string;
    reversal_command: string;
    timeout_seconds: number;
  }>;
  requires_human_approval: boolean;
  approval_desk_role: string;
}

export interface PromotionRecord {
  promotion_id: string;
  candidate_id: string;
  validation_id: string;
  canonical_from: string;
  relation: string;
  canonical_to: string;
  display_from: string;
  display_relation: string;
  display_to: string;
  status: KnowledgePromotionState;
  provenance: Record<string, unknown>;
  rollback_supported: boolean;
}

export interface LearningLedgerEntry {
  knowledge_id: string;
  display_name: string;
  canonical_from: string;
  relation: string;
  canonical_to: string;
  state: KnowledgePromotionState;
  discovered_in: string;
  validated_by: string;
  reused_in: string[];
  helpful_reuse_count: number;
  harmful_reuse_count: number;
  last_verified_at: string;
}

// ============================================================================
// 3. Tier 2: Operational Orchestration & Governance (Zaki)
// ============================================================================

export interface TaskEpisodeContract {
  api_version: string;
  kind: "TaskEpisode";
  episode_id: string;
  task_id: string;
  incident_id: string;
  operator_intent: string;
  fcaps: {
    primary: string;
    secondary: string[];
    domain: string;
    confidence: number;
    clarification_required: boolean;
  };
  domains: string[];
  context: Record<string, unknown>;
  operational_context_ref?: string | null;
  behavior_contract_ref?: string | null;
  evidence_requested: string[];
  evidence_observed: string[];
  ranked_hypotheses: Array<Record<string, unknown>>;
  discrimination_probes: Array<Record<string, unknown>>;
  selected_workflow?: string | null;
  playbook_ref?: string | null;
  agent_recommendation?: string | null;
  human_validations: Array<Record<string, unknown>>;
  human_actions: Array<Record<string, unknown>>;
  human_corrections: Array<Record<string, unknown>>;
  outcome: string;
  learned_pattern?: Record<string, unknown> | null;
  provenance: string;
  created_at: string;
  closed_at?: string | null;
}

export interface OperationalContextContract {
  api_version: string;
  kind: "OperationalContext";
  context_id: string;
  incident_anchor: {
    incident_id: string;
    start_time: string;
    active_duration_minutes: number;
    status: string;
    severity: string;
    hidden_ground_truth_barrier: boolean;
  };
  temporal_baseline: {
    pre_incident_changes_count: number;
    recent_change_requests: Array<Record<string, unknown>>;
    first_anomaly_timestamp?: string | null;
    baseline_window_hours: number;
  };
  topology_and_redundancy: {
    primary_service_path: string[];
    downstream_dependencies: string[];
    redundancy_state: string;
    ha_backup_paths: Array<Record<string, unknown>>;
    unprotected_spofs: string[];
  };
  investigation_memory: {
    completed_checks: string[];
    ruled_out_hypotheses: string[];
    active_checks: string[];
    pending_probes: string[];
  };
  blast_radius: BlastRadiusAssessment;
  operational_activity: {
    lead_domain_agent?: string | null;
    assigned_desk_lead?: string | null;
    shift_handover_notes: string[];
    active_playbook_ref?: string | null;
  };
  created_at: string;
}

export interface BehaviorContract {
  api_version: string;
  kind: "BehaviorContract";
  profile_name: string;
  target_role: string;
  forbid_arbitrary_percentages: boolean;
  forbid_premature_rca: boolean;
  observation_not_causation: boolean;
  forbid_hidden_oracle_leakage: boolean;
  safety_tier: ActionSafetyTier;
  require_hitl_for_disruptive: boolean;
  require_verified_rollback_plan: boolean;
  target_desk: string;
  mandate_difference_articulation: boolean;
  required_similarity_threshold: number;
  cite_historical_episodes: boolean;
  narration_mode: "SPEECH_PACED" | "REALTIME" | "SILENT";
  drop_voice_allowed: boolean;
  queue_overlap_allowed: boolean;
  acronym_prosody_expansion: boolean;
  human_readable_telecom_terms: boolean;
  speech_completion_barrier_required: boolean;
}

export interface HumanValidationContract {
  metadata: {
    id: string;
    task_id: string;
    incident_id: string;
    domain: string;
    originating_agent_id?: string | null;
  };
  spec: {
    decision: ValidationDecisionType;
    target_type: string;
    target_id: string;
    reason: string;
    validator_role: string;
    validator_id: string;
    authority: AuthorityLevel;
    timestamp: string;
    provenance: string;
    modifications?: Record<string, unknown> | null;
  };
}
"""

output_file.write_text(ts_content, encoding="utf-8")
print(f"Generated TypeScript contracts at: {output_file}")
