apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agenticaiops-secops
  namespace: argocd
spec:
  project: agenticaiops
  source:
    repoURL: "https://github.com/adeelarshad/kagent"
    targetRevision: main
    path: deploy/kagent/secops
  destination:
    server: "https://kubernetes.default.svc"
    namespace: agents-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
